<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="triciclo_robot">

  <!-- Parámetros base -->
  <xacro:property name="base_length" value="0.42"/>
  <xacro:property name="base_width" value="0.31"/>
  <xacro:property name="base_height" value="0.18"/>

  <!-- Parámetros ruedas -->
  <xacro:property name="rear_wheel_radius" value="0.1"/>
  <xacro:property name="rear_wheel_width" value="0.05"/>
  <xacro:property name="front_wheel_radius" value="0.1"/>
  <xacro:property name="front_wheel_width" value="0.05"/>

  <!-- Macros para inercia -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <mass value="${m}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="${(m/12)*(h*h + d*d)}"
        ixy="0"
        ixz="0"
        iyy="${(m/12)*(w*w + d*d)}"
        iyz="0"
        izz="${(m/12)*(w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="${(m/12)*(3*r*r + h*h)}"
        ixy="0"
        ixz="0"
        iyy="${(m/12)*(3*r*r + h*h)}"
        iyz="0"
        izz="${(m/2)*(r*r)}"/>
    </inertial>
  </xacro:macro>

  <!-- BASE -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2 + rear_wheel_radius}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Blue">
        <color rgba="0.0 0.5 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2 + rear_wheel_radius}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="5" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>

  <!-- LINK intermedio para la dirección -->
  <link name="front_wheel_steering_link">
    <!-- Agregamos una masa mínima para que Gazebo no falle -->
    <visual>
      <geometry>
        <sphere radius="0.001"/>
      </geometry>
      <material name="invisible"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.001"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
  </link>

  <!-- Junta de dirección -->
  <joint name="steering_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_wheel_steering_link"/>
    <origin xyz="${base_length/2 - 0.05} 0 ${rear_wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.6" upper="0.6" effort="5" velocity="1"/>
  </joint>

  <!-- RUEDA DELANTERA -->
  <link name="front_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${front_wheel_radius}" length="${front_wheel_width}"/>
      </geometry>
      <material name="Gray">
       <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${front_wheel_radius}" length="${front_wheel_width}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.2" r="${front_wheel_radius}" h="${front_wheel_width}"/>
  </link>

  <!-- Junta de rotación de la rueda delantera -->
  <joint name="front_wheel_joint" type="continuous">
    <parent link="front_wheel_steering_link"/>
    <child link="front_wheel_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- RUEDA TRASERA IZQUIERDA -->
  <link name="rear_left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${rear_wheel_radius}" length="${rear_wheel_width}"/>
      </geometry>
      <material name="Gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${rear_wheel_radius}" length="${rear_wheel_width}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.2" r="${rear_wheel_radius}" h="${rear_wheel_width}"/>
  </link>

  <joint name="rear_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_left_wheel"/>
    <origin xyz="-${base_length/2 - 0.02} ${base_width/2 - 0.02} ${rear_wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- RUEDA TRASERA DERECHA -->
  <link name="rear_right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${rear_wheel_radius}" length="${rear_wheel_width}"/>
      </geometry>
      <material name="Gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${rear_wheel_radius}" length="${rear_wheel_width}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.2" r="${rear_wheel_radius}" h="${rear_wheel_width}"/>
  </link>

  <joint name="rear_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_right_wheel"/>
    <origin xyz="-${base_length/2 - 0.02} -${base_width/2 - 0.02} ${rear_wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>


<!-- ros2_control Plugin -->
<gazebo>
  <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <robot_param>robot_description</robot_param>
      <robot_param_node>robot_state_publisher</robot_param_node>
      <parameters>$(find triciclo_robot)/config/triciclo_controllers.yaml</parameters>
  </plugin>
</gazebo>

<!-- Transmisiones para control -->
<transmission name="steering_transmission">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="steering_joint">
    <hardwareInterface>position</hardwareInterface>
  </joint>
  <actuator name="steering_motor">
    <hardwareInterface>position</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<transmission name="front_drive_transmission">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="front_wheel_joint">
    <hardwareInterface>velocity</hardwareInterface>
  </joint>
  <actuator name="front_drive_motor">
    <hardwareInterface>velocity</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<ros2_control name="TricicloSystem" type="system">
  <hardware>
    <plugin>gazebo_ros2_control/DefaultRobotHWSim</plugin>
  </hardware>


  <joint name="steering_joint">
    <command_interface name="position"/>
    <state_interface name="position"/>
    <state_interface name="velocity"/>
  </joint>

  <joint name="front_wheel_joint">
    <command_interface name="velocity"/>
    <state_interface name="position"/>
    <state_interface name="velocity"/>
  </joint>
</ros2_control>


</robot>
